spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  output:
    ansi:
      enabled: always
logging:
  level:
    root: info
