logging:
  level:
    root: info
spring:
  flyway:
    baselineOnMigrate: true
    locations: classpath:db/migration/prod
    enabled: true
application:
  bucket:
    name: 2021-jujeol-test
  cloudfront:
    url: https://didenwe6zsh18.cloudfront.net/
