logging:
  level:
    root: info
spring:
  flyway:
    baselineOnMigrate: true
    locations: classpath:db/migration/prod
    enabled: false
application:
  bucket:
    name: jujeol-bucket
  cloudfront:
    url: https://dmaxaug2ve9od.cloudfront.net/