logging:
  level:
    root: info
decorator:
  datasource:
    p6spy:
      enable-logging: false
spring:
  flyway:
    baselineOnMigrate: true
    locations: classpath:db/migration/prod
    enabled: true
application:
  bucket:
    name: jujeol-bucket
  cloudfront:
    url: https://dmaxaug2ve9od.cloudfront.net/