logging:
  level:
    root: info
spring:
  flyway:
    baselineOnMigrate: true
    locations: classpath:db/migration/prod
    enabled: true
application:
  bucket:
    name: jujeol-image
  cloudfront:
    url: https://d1sqi8cd60mbpv.cloudfront.net/