# test.yml
name: test

on:
#  push:
  pull_request:
    branches:
      - test/github-action-config    # gitub-action-config 브랜치에서 pr 이벤트가 일어났을 때 실행
    types: published
      
defaults:
  run:
    working-directory: ./frontend

jobs:
  build:
    runs-on: test-actions
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build:dev

      - name: Deploy
        run: aws s3 sync ./build s3://jujeol-dev-depoly
